site_name: Escher-Trace
nav:
        - 1. Getting Started with Escher-Trace: GettingStarted.md
        - 2. Edit Individual Graphs: EditIndivGraphs.md
        - 3. Changing the Displayed Graph Type: GraphTypes.md
        - 4. Changing Graph Attributes: GraphAttributes.md
        - 5. Changing Data Displayed: DataDisplayed.md
        - 6. Analysis: Analysis.md
        - 7. Edit the Data: EditData.md
        - 8. Save Workspace: SaveWorkspace.md
    
theme: 'rtd-dropdown'
markdown_extensions:
    - attr_list
